//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActivityMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Activity already exists!.
        /// </summary>
        internal static string ActivityAlreadyExists {
            get {
                return ResourceManager.GetString("ActivityAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Activity was created sucesfully..
        /// </summary>
        internal static string ActivityWasCreated {
            get {
                return ResourceManager.GetString("ActivityWasCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Statistics.
        /// </summary>
        internal static string ContextMenuStatistics {
            get {
                return ResourceManager.GetString("ContextMenuStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Confirm delete.
        /// </summary>
        internal static string DeleteActivityConfirm {
            get {
                return ResourceManager.GetString("DeleteActivityConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Do you really want to delete activity? {0}.
        /// </summary>
        internal static string DeleteActivityConfirmation {
            get {
                return ResourceManager.GetString("DeleteActivityConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error saving changes: {0}.
        /// </summary>
        internal static string ErrorSavingChanges {
            get {
                return ResourceManager.GetString("ErrorSavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Begin.
        /// </summary>
        internal static string HtmlTemplateBegin {
            get {
                return ResourceManager.GetString("HtmlTemplateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Duration.
        /// </summary>
        internal static string HtmlTemplateDuration {
            get {
                return ResourceManager.GetString("HtmlTemplateDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný End.
        /// </summary>
        internal static string HtmlTemplateEnd {
            get {
                return ResourceManager.GetString("HtmlTemplateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný File.
        /// </summary>
        internal static string HtmlTemplateFile {
            get {
                return ResourceManager.GetString("HtmlTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný en.
        /// </summary>
        internal static string HtmlTemplateLang {
            get {
                return ResourceManager.GetString("HtmlTemplateLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Statistics.
        /// </summary>
        internal static string HtmlTemplateStatistics {
            get {
                return ResourceManager.GetString("HtmlTemplateStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Total duration.
        /// </summary>
        internal static string HtmlTemplateTotalDuration {
            get {
                return ResourceManager.GetString("HtmlTemplateTotalDuration", resourceCulture);
            }
        }
    }
}
